UPDATE blog_posts
SET translations = translations || $json$ {
  "es": {
    "title": "Posiciones de fútbol y sus roles: una guía completa",
    "category": "Fútbol",
    "excerpt": "El fútbol, conocido por su estrategia y fluidez, depende en gran medida de los roles distintos de los jugadores en el campo.",
    "content": "<h2><strong>Comprender las posiciones de fútbol y sus roles</strong></h2><p>El fútbol es un deporte altamente estratégico donde cada jugador tiene un papel claramente definido.</p><h2><strong>1. Portero (GK)</strong></h2><p>Última línea de defensa, el único jugador que puede usar las manos dentro del área penal.</p><h2><strong>2. Defensores</strong></h2><ul><li>Centrales (CB) operan en áreas centrales.</li><li>Laterales (LB &amp; RB) juegan anchos en defensa.</li><li>Carrileros (LWB &amp; RWB) son laterales más ofensivos.</li></ul><h2><strong>3. Centrocampistas</strong></h2><ul><li>Centrocampistas defensivos (CDM) protegen la defensa.</li><li>Centrocampistas centrales (CM) equilibran tareas defensivas con pases hacia adelante.</li><li>Centrocampistas ofensivos (CAM) operan cerca del gol rival.</li><li>Centrocampistas de banda (LM/RM) proporcionan amplitud.</li></ul><h2><strong>4. Delanteros</strong></h2><ul><li>Delanteros (ST) suelen liderar la línea.</li><li>Mediapuntas (CF) pueden retroceder para enlazar jugadas.</li><li>Extremos (LW/RW) estiran la defensa.</li></ul><h2><strong>5. Importancia del juego posicional</strong></h2><p>El éxito de un equipo depende de que cada jugador entienda sus responsabilidades y cómo su posición encaja en el plan táctico general.</p>"
  },
  "fr": {
    "title": "Positions de football et leurs rôles : un guide complet",
    "category": "Football",
    "excerpt": "Le football, connu pour sa stratégie et sa fluidité, repose fortement sur les rôles distincts des joueurs sur le terrain.",
    "content": "<h2><strong>Comprendre les positions de football et leurs rôles</strong></h2><p>Le football est un sport hautement stratégique où chaque joueur a un rôle clairement défini.</p><h2><strong>1. Gardien de but (GK)</strong></h2><p>Dernière ligne de défense, seul joueur autorisé à utiliser ses mains dans la surface de réparation.</p><h2><strong>2. Défenseurs</strong></h2><ul><li>Défenseurs centraux (DC) opèrent dans les zones centrales.</li><li>Arrières latéraux (LB &amp; RB) jouent larges en défense.</li><li>Latéraux offensifs (LWB &amp; RWB) sont des arrières plus offensifs.</li></ul><h2><strong>3. Milieux de terrain</strong></h2><ul><li>Milieux défensifs (MDF) protègent la défense.</li><li>Milieux centraux (MC) équilibrent tâches défensives et passes vers l'avant.</li><li>Milieux offensifs (MO) opèrent près du but adverse.</li><li>Milieux de terrain excentrés (LM/RM) apportent de la largeur.</li></ul><h2><strong>4. Attaquants</strong></h2><ul><li>Buteurs (BT) dirigent généralement la ligne.</li><li>Attaquants centraux (AC) peuvent descendre plus bas pour lier le jeu.</li><li>Ailiers (AG/AD) étirent la défense.</li></ul><h2><strong>5. Importance du jeu de position</strong></h2><p>Le succès d'une équipe dépend de la compréhension par chaque joueur de ses responsabilités et de la manière dont sa position s'intègre au plan tactique global.</p>"
  },
  "de": {
    "title": "Fußballpositionen und ihre Rollen: Ein kompletter Leitfaden",
    "category": "Fußball",
    "excerpt": "Fußball, bekannt für seine Strategie und Flüssigkeit, verlässt sich stark auf die unterschiedlichen Rollen der Spieler auf dem Feld.",
    "content": "<h2><strong>Verständnis der Fußballpositionen und ihrer Rollen</strong></h2><p>Fußball ist ein hochstrategischer Sport, bei dem jeder Spieler eine klar definierte Rolle hat.</p><h2><strong>1. Torwart (GK)</strong></h2><p>Letzte Verteidigungslinie, einziger Spieler, der die Hände innerhalb des Strafraums benutzen darf.</p><h2><strong>2. Verteidiger</strong></h2><ul><li>Innenverteidiger (IV) agieren in zentralen Bereichen.</li><li>Außenverteidiger (LV &amp; RV) spielen breit in der Abwehr.</li><li>Flügelverteidiger (LWB &amp; RWB) sind offensivere Außenverteidiger.</li></ul><h2><strong>3. Mittelfeldspieler</strong></h2><ul><li>Defensive Mittelfeldspieler (DM) schützen die Abwehr.</li><li>Zentrale Mittelfeldspieler (ZM) gleichen defensive Aufgaben mit Vorwärtspässen aus.</li><li>Offensive Mittelfeldspieler (OM) agieren näher am gegnerischen Tor.</li><li>Flügelspieler (LM/RM) sorgen für Breite.</li></ul><h2><strong>4. Stürmer</strong></h2><ul><li>Stürmer (ST) führen typischerweise die Linie an.</li><li>Mittelstürmer (MS) können tiefer fallen, um das Spiel zu verbinden.</li><li>Flügelspieler (LA/RA) dehnen die Abwehr.</li></ul><h2><strong>5. Bedeutung des Positionsspiels</strong></h2><p>Der Erfolg eines Teams hängt davon ab, dass jeder Spieler seine Verantwortlichkeiten versteht und wie seine Position in den gesamten taktischen Plan passt.</p>"
  },
  "it": {
    "title": "Posizioni del calcio e i loro ruoli: una guida completa",
    "category": "Calcio",
    "excerpt": "Il calcio, noto per la sua strategia e fluidità, si basa molto sui ruoli distinti dei giocatori in campo.",
    "content": "<h2><strong>Comprendere le posizioni del calcio e i loro ruoli</strong></h2><p>Il calcio è uno sport altamente strategico in cui ogni giocatore ha un ruolo chiaramente definito.</p><h2><strong>1. Portiere (GK)</strong></h2><p>L'ultima linea di difesa, l'unico giocatore a cui è permesso usare le mani all'interno dell'area di rigore.</p><h2><strong>2. Difensori</strong></h2><ul><li>Difensori centrali (DC) operano nelle zone centrali.</li><li>Terzini (TS &amp; TD) giocano ampiamente in difesa.</li><li>Esterni di centrocampo (LWB &amp; RWB) sono terzini più offensivi.</li></ul><h2><strong>3. Centrocampisti</strong></h2><ul><li>Centrocampisti difensivi (CDC) proteggono la difesa.</li><li>Centrocampisti centrali (CC) bilanciano compiti difensivi con passaggi in avanti.</li><li>Centrocampisti offensivi (COC) operano più vicino alla porta avversaria.</li><li>Esterni di centrocampo (ES/ED) forniscono ampiezza.</li></ul><h2><strong>4. Attaccanti</strong></h2><ul><li>Attaccanti (AT) di solito guidano la linea.</li><li>Punte centrali (PC) possono arretrare per collegare il gioco.</li><li>Ali (AS/AD) allargano la difesa.</li></ul><h2><strong>5. Importanza del gioco di posizione</strong></h2><p>Il successo di una squadra dipende dal fatto che ogni giocatore comprenda le proprie responsabilità e come la propria posizione si adatti al piano tattico generale.</p>"
  },
  "pt": {
    "title": "Posições do futebol e seus papéis: um guia completo",
    "category": "Futebol",
    "excerpt": "O futebol, conhecido por sua estratégia e fluidez, depende muito dos papéis distintos dos jogadores em campo.",
    "content": "<h2><strong>Entendendo as posições do futebol e seus papéis</strong></h2><p>O futebol é um esporte altamente estratégico, onde cada jogador tem um papel claramente definido.</p><h2><strong>1. Goleiro (GK)</strong></h2><p>Última linha de defesa, o único jogador autorizado a usar as mãos dentro da área penal.</p><h2><strong>2. Defensores</strong></h2><ul><li>Zagueiros (ZG) operam em áreas centrais.</li><li>Laterais (LE &amp; LD) jogam abertos na defesa.</li><li>Alas (AL &amp; AD) são laterais mais ofensivos.</li></ul><h2><strong>3. Meio-campistas</strong></h2><ul><li>Volantes (VOL) protegem a defesa.</li><li>Meias centrais (MC) equilibram tarefas defensivas com passes para a frente.</li><li>Meias-atacantes (MA) operam mais perto do gol adversário.</li><li>Meias-abertos (ME/MD) fornecem largura.</li></ul><h2><strong>4. Atacantes</strong></h2><ul><li>Atacantes (AT) geralmente lideram a linha.</li><li>Centroavantes (CA) podem recuar para ligar o jogo.</li><li>Pontas (PE/PD) abrem a defesa.</li></ul><h2><strong>5. Importância do jogo posicional</strong></h2><p>O sucesso de uma equipe depende de cada jogador entender suas responsabilidades e como sua posição se encaixa no plano tático geral.</p>"
  },
  "ru": {
    "title": "Футбольные позиции и их роли: полное руководство",
    "category": "Футбол",
    "excerpt": "Футбол, известный своей стратегией и плавностью, сильно зависит от различных ролей игроков на поле.",
    "content": "<h2><strong>Понимание футбольных позиций и их ролей</strong></h2><p>Футбол — это высокостратегический вид спорта, где у каждого игрока есть четко определенная роль.</p><h2><strong>1. Вратарь (ВР)</strong></h2><p>Последняя линия обороны, единственный игрок, которому разрешено использовать руки в штрафной площади.</p><h2><strong>2. Защитники</strong></h2><ul><li>Центральные защитники (ЦЗ) действуют в центральных зонах.</li><li>Крайние защитники (ЛЗ &amp; ПЗ) играют широко в защите.</li><li>Вингбэки (ЛВБ &amp; ПВБ) являются более атакующими крайними защитниками.</li></ul><h2><strong>3. Полузащитники</strong></h2><ul><li>Опорные полузащитники (ОП) защищают оборону.</li><li>Центральные полузащитники (ЦП) балансируют оборонительные обязанности с передачами вперед.</li><li>Атакующие полузащитники (АП) действуют ближе к воротам соперника.</li><li>Крайние полузащитники (ЛМ/ПМ) обеспечивают ширину.</li></ul><h2><strong>4. Нападающие</strong></h2><ul><li>Нападающие (НП) обычно возглавляют линию.</li><li>Центрфорварды (ЦФ) могут опускаться глубже, чтобы связывать игру.</li><li>Вингеры (ЛВ/ПВ) растягивают оборону.</li></ul><h2><strong>5. Важность позиционной игры</strong></h2><p>Успех команды зависит от того, насколько каждый игрок понимает свои обязанности и как его позиция вписывается в общий тактический план.</p>"
  },
  "pl": {
    "title": "Pozycje w piłce nożnej i ich role: Kompletny przewodnik",
    "category": "Piłka nożna",
    "excerpt": "Piłka nożna, znana ze swojej strategii i płynności, w dużym stopniu opiera się na odrębnych rolach zawodników na boisku.",
    "content": "<h2><strong>Zrozumienie pozycji w piłce nożnej i ich ról</strong></h2><p>Piłka nożna to wysoce strategiczny sport, w którym każdy zawodnik ma jasno określoną rolę.</p><h2><strong>1. Bramkarz (BR)</strong></h2><p>Ostatnia linia obrony, jedyny zawodnik, który może używać rąk w polu karnym.</p><h2><strong>2. Obrońcy</strong></h2><ul><li>Środkowi obrońcy (ŚO) działają w centralnych obszarach.</li><li>Boczni obrońcy (LO &amp; PO) grają szeroko w obronie.</li><li>Wahadłowi (LWB &amp; RWB) to bardziej ofensywni boczni obrońcy.</li></ul><h2><strong>3. Pomocnicy</strong></h2><ul><li>Defensywni pomocnicy (DP) chronią obronę.</li><li>Środkowi pomocnicy (ŚP) równoważą obowiązki defensywne z podaniami do przodu.</li><li>Ofensywni pomocnicy (OP) działają bliżej bramki przeciwnika.</li><li>Skrzydłowi (LS/PS) zapewniają szerokość.</li></ul><h2><strong>4. Napastnicy</strong></h2><ul><li>Napastnicy (N) zazwyczaj prowadzą linię.</li><li>Środkowi napastnicy (CN) mogą opuszczać się głębiej, aby łączyć grę.</li><li>Skrzydłowi (LS/PS) rozciągają obronę.</li></ul><h2><strong>5. Znaczenie gry pozycyjnej</strong></h2><p>Sukces zespołu zależy od tego, czy każdy zawodnik rozumie swoje obowiązki i jak jego pozycja pasuje do ogólnego planu taktycznego.</p>"
  },
  "nl": {
    "title": "Voetbalposities en hun rollen: een uitgebreide gids",
    "category": "Voetbal",
    "excerpt": "Voetbal, bekend om zijn strategie en vloeibaarheid, leunt zwaar op de verschillende rollen van spelers op het veld.",
    "content": "<h2><strong>Voetbalposities en hun rollen begrijpen</strong></h2><p>Voetbal is een zeer strategische sport waarbij elke speler een duidelijk gedefinieerde rol heeft.</p><h2><strong>1. Doelman (DM)</strong></h2><p>De laatste verdedigingslinie, de enige speler die zijn handen mag gebruiken in het strafschopgebied.</p><h2><strong>2. Verdedigers</strong></h2><ul><li>Centrale verdedigers (CV) opereren in centrale gebieden.</li><li>Vleugelverdedigers (LV &amp; RV) spelen breed in de verdediging.</li><li>Wingbacks (LWB &amp; RWB) zijn offensievere vleugelverdedigers.</li></ul><h2><strong>3. Middenvelders</strong></h2><ul><li>Verdedigende middenvelders (VDM) beschermen de verdediging.</li><li>Centrale middenvelders (CM) balanceren defensieve taken met voorwaartse passes.</li><li>Aanvallende middenvelders (AM) opereren dichter bij het doel van de tegenstander.</li><li>Brede middenvelders (LM/RM) zorgen voor breedte.</li></ul><h2><strong>4. Aanvallers</strong></h2><ul><li>Spitsen (SP) leiden typisch de lijn.</li><li>Centrale aanvallers (CA) kunnen dieper vallen om het spel te verbinden.</li><li>Vleugelspelers (LV/RV) rekken de verdediging uit.</li></ul><h2><strong>5. Belang van positie-spel</strong></h2><p>Het succes van een team hangt af van het feit dat elke speler zijn verantwoordelijkheden begrijpt en hoe zijn positie in het algehele tactische plan past.</p>"
  },
  "sv": {
    "title": "Fotbollspositioner och deras roller: En komplett guide",
    "category": "Fotboll",
    "excerpt": "Fotboll, känt för sin strategi och smidighet, förlitar sig mycket på spelarnas distinkta roller på planen.",
    "content": "<h2><strong>Förstå fotbollspositioner och deras roller</strong></h2><p>Fotboll är en mycket strategisk sport där varje spelare har en tydligt definierad roll.</p><h2><strong>1. Målvakt (MV)</strong></h2><p>Den sista försvarslinjen, den enda spelaren som får använda händerna inom straffområdet.</p><h2><strong>2. Försvarare</strong></h2><ul><li>Mittbackar (MB) opererar i centrala områden.</li><li>Ytterbackar (VB &amp; HB) spelar brett i försvaret.</li><li>Wingbacks (VWB &amp; HWB) är mer offensiva ytterbackar.</li></ul><h2><strong>3. Mittfältare</strong></h2><ul><li>Defensiva mittfältare (DM) skyddar försvaret.</li><li>Centrala mittfältare (CM) balanserar defensiva uppgifter med framåtpassningar.</li><li>Offensiva mittfältare (OM) opererar närmare motståndarens mål.</li><li>Yttermittfältare (VM/HM) ger bredd.</li></ul><h2><strong>4. Anfallare</strong></h2><ul><li>Anfallare (ANF) leder typiskt linjen.</li><li>Centrala anfallare (CA) kan falla djupare för att länka spelet.</li><li>Ytteranfallare (VA/HA) sträcker ut försvaret.</li></ul><h2><strong>5. Betydelsen av positionsspel</strong></h2><p>Ett lags framgång beror på att varje spelare förstår sina ansvarsområden och hur deras position passar in i den övergripande taktiska planen.</p>"
  },
  "no": {
    "title": "Fotballposisjoner og deres roller: En komplett guide",
    "category": "Fotball",
    "excerpt": "Fotball, kjent for sin strategi og flyt, er sterkt avhengig av spillernes distinkte roller på banen.",
    "content": "<h2><strong>Forstå fotballposisjoner og deres roller</strong></h2><p>Fotball er en svært strategisk sport der hver spiller har en klart definert rolle.</p><h2><strong>1. Keeper (K)</strong></h2><p>Den siste forsvarslinjen, den eneste spilleren som har lov til å bruke hendene innenfor straffefeltet.</p><h2><strong>2. Forsvarere</strong></h2><ul><li>Midtstoppere (MS) opererer i sentrale områder.</li><li>Sidebacker (VB &amp; HB) spiller bredt i forsvaret.</li><li>Vingbacker (VWB &amp; HWB) er mer offensive sidebacker.</li></ul><h2><strong>3. Midtbane</strong></h2><ul><li>Defensive midtbanespillere (DM) beskytter forsvaret.</li><li>Sentrale midtbanespillere (SM) balanserer defensive oppgaver med fremoverpasninger.</li><li>Offensive midtbanespillere (OM) opererer nærmere motstanderens mål.</li><li>Kantspillere (VM/HM) gir bredde.</li></ul><h2><strong>4. Angripere</strong></h2><ul><li>Spisser (SP) leder typisk linjen.</li><li>Midtspisser (MP) kan falle dypere for å knytte sammen spillet.</li><li>Vinger (VV/HV) strekker forsvaret.</li></ul><h2><strong>5. Viktigheten av posisjonsspill</strong></h2><p>Et lags suksess avhenger av at hver spiller forstår sine ansvarsområder og hvordan deres posisjon passer inn i den overordnede taktiske planen.</p>"
  },
  "da": {
    "title": "Fodboldpositioner og deres roller: En komplet guide",
    "category": "Fodbold",
    "excerpt": "Fodbold, kendt for sin strategi og flydende spil, er stærkt afhængig af spillernes forskellige roller på banen.",
    "content": "<h2><strong>Forståelse af fodboldpositioner og deres roller</strong></h2><p>Fodbold er en meget strategisk sport, hvor hver spiller har en klart defineret rolle.</p><h2><strong>1. Målmand (MM)</strong></h2><p>Den sidste forsvarslinje, den eneste spiller, der må bruge hænderne i straffesparksfeltet.</p><h2><strong>2. Forsvarere</strong></h2><ul><li>Centralforsvarere (CF) opererer i centrale områder.</li><li>Backs (LB &amp; RB) spiller bredt i forsvaret.</li><li>Wingbacks (LWB &amp; RWB) er mere offensive backs.</li></ul><h2><strong>3. Midtbanespillere</strong></h2><ul><li>Defensive midtbanespillere (DM) beskytter forsvaret.</li><li>Centrale midtbanespillere (CM) balancerer defensive opgaver med fremadrettede afleveringer.</li><li>Offensive midtbanespillere (OM) opererer tættere på modstanderens mål.</li><li>Brede midtbanespillere (LM/RM) giver bredde.</li></ul><h2><strong>4. Angribere</strong></h2><ul><li>Angribere (ANF) fører typisk linjen.</li><li>Centrale angribere (CA) kan falde dybere for at forbinde spillet.</li><li>Fløjspillere (VF/HF) strækker forsvaret.</li></ul><h2><strong>5. Betydningen af positionsspil</strong></h2><p>Et holds succes afhænger af, at hver spiller forstår sine ansvarsområder, og hvordan deres position passer ind i den overordnede taktiske plan.</p>"
  },
  "fi": {
    "title": "Jalkapallopelipaikat ja niiden roolit: Täydellinen opas",
    "category": "Jalkapallo",
    "excerpt": "Jalkapallo, joka tunnetaan strategiastaan ja sujuvuudestaan, luottaa voimakkaasti pelaajien erillisiin rooleihin kentällä.",
    "content": "<h2><strong>Jalkapallopelipaikkojen ja niiden roolien ymmärtäminen</strong></h2><p>Jalkapallo on erittäin strateginen urheilulaji, jossa jokaisella pelaajalla on selkeästi määritelty rooli.</p><h2><strong>1. Maalivahti (MV)</strong></h2><p>Puolustuksen viimeinen linja, ainoa pelaaja, joka saa käyttää käsiään rangaistusalueella.</p><h2><strong>2. Puolustajat</strong></h2><ul><li>Keskimiehiksi (KK) kutsutut puolustajat toimivat keskeisillä alueilla.</li><li>Laitapuolustajat (LP &amp; RP) pelaavat leveästi puolustuksessa.</li><li>Wingbackit (LWB &amp; RWB) ovat hyökkäävämpiä laitapuolustajia.</li></ul><h2><strong>3. Keskikenttäpelaajat</strong></h2><ul><li>Puolustavat keskikenttäpelaajat (PKK) suojelevat puolustusta.</li><li>Keskikenttäpelaajat (KKP) tasapainottavat puolustustehtäviä ja eteenpäin syöttämistä.</li><li>Hyökkäävät keskikenttäpelaajat (HKK) toimivat lähempänä vastustajan maalia.</li><li>Laidalla pelaavat keskikenttäpelaajat (LM/RM) antavat leveyttä.</li></ul><h2><strong>4. Hyökkääjät</strong></h2><ul><li>Hyökkääjät (H) johtavat tyypillisesti linjaa.</li><li>Keskushyökkääjät (KH) voivat pudota syvemmälle linkittämään peliä.</li><li>Laitahyökkääjät (LH/RH) venyttävät puolustusta.</li></ul><h2><strong>5. Paikkapelin merkitys</strong></h2><p>Joukkueen menestys riippuu siitä, että jokainen pelaaja ymmärtää vastuunsa ja miten hänen positionsa sopii kokonaisvaltaiseen taktiseen suunnitelmaan.</p>"
  }
} $json$::jsonb
WHERE slug = 'understanding-football-positions-and-their-roles';
