UPDATE blog_posts
SET translations = translations || $json$ {
  "ar": {
    "title": "مراكز كرة القدم وأدوارها: دليل كامل",
    "category": "كرة القدم",
    "excerpt": "تعتمد كرة القدم، المعروفة باستراتيجيتها وسلاستها، بشكل كبير على الأدوار المتميزة للاعبين في الملعب.",
    "content": "<h2><strong>فهم مراكز كرة القدم وأدوارها</strong></h2><p>كرة القدم هي رياضة استراتيجية للغاية حيث لكل لاعب دور محدد بوضوح.</p><h2><strong>1. حارس المرمى (GK)</strong></h2><p>خط الدفاع الأخير، اللاعب الوحيد المسموح له باستخدام يديه داخل منطقة الجزاء.</p><h2><strong>2. المدافعون</strong></h2><ul><li>المدافعون المركزيون (CB) يعملون في المناطق المركزية.</li><li>المدافعون الجانبيون (LB &amp; RB) يلعبون على نطاق واسع في الدفاع.</li><li>أظهرة الأجنحة (LWB &amp; RWB) هم مدافعون جانبيون أكثر هجومية.</li></ul><h2><strong>3. لاعبو خط الوسط</strong></h2><ul><li>لاعبو الوسط الدفاعيون (CDM) يحمون الدفاع.</li><li>لاعبو الوسط المركزيون (CM) يوازنون الواجبات الدفاعية مع التمرير الأمامي.</li><li>لاعبو الوسط المهاجمون (CAM) يعملون بالقرب من مرمى الخصم.</li><li>لاعبو الوسط العريضون (LM/RM) يوفرون العرض.</li></ul><h2><strong>4. المهاجمون</strong></h2><ul><li>المهاجمون (ST) عادة ما يقودون الخط.</li><li>المهاجمون المركزيون (CF) قد يتراجعون للربط بين اللعب.</li><li>الأجنحة (LW/RW) يوسعون الدفاع.</li></ul><h2><strong>5. أهمية اللعب الموضعي</strong></h2><p>يعتمد نجاح الفريق على فهم كل لاعب لمسؤولياته وكيف يتناسب موقعه مع الخطة التكتيكية الشاملة.</p>"
  },
  "he": {
    "title": "עמדות כדורגל ותפקידיהן: מדריך מלא",
    "category": "כדורגל",
    "excerpt": "כדורגל, הידוע באסטרטגיה ובזרימה שלו, מסתמך רבות על התפקידים המובחנים של שחקנים במגרש.",
    "content": "<h2><strong>הבנת עמדות כדורגל ותפקידיהן</strong></h2><p>כדורגל הוא ספורט אסטרטגי מאוד שבו לכל שחקן יש תפקיד מוגדר בבירור.</p><h2><strong>1. שוער (GK)</strong></h2><p>קו ההגנה האחרון, השחקן היחיד המורשה להשתמש בידיו בתוך רחבת העונשין.</p><h2><strong>2. מגינים</strong></h2><ul><li>בלמים (בלם) פועלים באזורים מרכזיים.</li><li>מגנים צדדיים (מגן שמאלי ומגן ימני) משחקים ברוחב ההגנה.</li><li>מגיני כנף (LWB &amp; RWB) הם מגנים צדדיים יותר התקפיים.</li></ul><h2><strong>3. קשרים</strong></h2><ul><li>קשרים הגנתיים (קשר אחורי) מגנים על ההגנה.</li><li>קשרים מרכזיים (קשר מרכזי) מאזנים חובות הגנתיות עם מסירות קדימה.</li><li>קשרים התקפיים (קשר קדמי) פועלים קרוב לשער היריב.</li><li>קשרי כנף (קשר ימני/שמאלי) מספקים רוחב.</li></ul><h2><strong>4. חלוצים</strong></h2><ul><li>חלוצים (חלוץ) מובילים בדרך כלל את הקו.</li><li>חלוצי מרכז (חלוץ מרכזי) יכולים לרדת עמוק יותר כדי לקשר את המשחק.</li><li>כנפיים (כנף שמאל/כנף ימין) מותחות את ההגנה.</li></ul><h2><strong>5. חשיבות משחק המיקום</strong></h2><p>הצלחת הקבוצה תלויה בכך שכל שחקן יבין את אחריותו וכיצד עמדתו משתלבת בתוכנית הטקטית הכוללת.</p>"
  },
  "fa": {
    "title": "موقعیت‌های فوتبال و نقش‌های آن‌ها: راهنمای کامل",
    "category": "فوتبال",
    "excerpt": "فوتبال، که به دلیل استراتژی و روانی خود شناخته شده است، به شدت به نقش‌های متمایز بازیکنان در زمین متکی است.",
    "content": "<h2><strong>درک موقعیت‌های فوتبال و نقش‌های آن‌ها</strong></h2><p>فوتبال یک ورزش بسیار استراتژیک است که در آن هر بازیکن نقشی کاملاً مشخص دارد.</p><h2><strong>1. دروازه‌بان (GK)</strong></h2><p>آخرین خط دفاعی، تنها بازیکنی است که اجازه دارد در داخل محوطه جریمه از دستان خود استفاده کند.</p><h2><strong>2. مدافعان</strong></h2><ul><li>مدافعان میانی (CB) در مناطق مرکزی فعالیت می‌کنند.</li><li>مدافعان کناری (LB &amp; RB) در دفاع به طور گسترده بازی می‌کنند.</li><li>وینگ‌بک‌ها (LWB &amp; RWB) مدافعان کناری تهاجمی‌تر هستند.</li></ul><h2><strong>3. هافبک‌ها</strong></h2><ul><li>هافبک‌های دفاعی (CDM) از دفاع محافظت می‌کنند.</li><li>هافبک‌های مرکزی (CM) وظایف دفاعی را با پاس‌های رو به جلو متعادل می‌کنند.</li><li>هافبک‌های تهاجمی (CAM) نزدیک‌تر به دروازه حریف عمل می‌کنند.</li><li>هافبک‌های کناری (LM/RM) عرض زمین را پوشش می‌دهند.</li></ul><h2><strong>4. مهاجمان</strong></h2><ul><li>مهاجمان (ST) معمولاً خط حمله را رهبری می‌کنند.</li><li>مهاجمان مرکزی (CF) ممکن است برای ارتباط بازی عمیق‌تر شوند.</li><li>وینگرها (LW/RW) دفاع را گسترش می‌دهند.</li></ul><h2><strong>5. اهمیت بازی موقعیتی</strong></h2><p>موفقیت یک تیم بستگی به درک هر بازیکن از مسئولیت‌های خود و چگونگی تناسب موقعیت آن‌ها با طرح تاکتیکی کلی دارد.</p>"
  },
  "tr": {
    "title": "Futbol Pozisyonları ve Rolleri: Tam Bir Kılavuz",
    "category": "Futbol",
    "excerpt": "Stratejisi ve akıcılığıyla bilinen futbol, sahadaki oyuncuların farklı rollerine büyük ölçüde dayanır.",
    "content": "<h2><strong>Futbol Pozisyonlarını ve Rollerini Anlamak</strong></h2><p>Futbol, her oyuncunun açıkça tanımlanmış bir role sahip olduğu son derece stratejik bir spordur.</p><h2><strong>1. Kaleci (GK)</strong></h2><p>Savunmanın son hattı, ceza sahası içinde ellerini kullanmasına izin verilen tek oyuncu.</p><h2><strong>2. Savunmacılar</strong></h2><ul><li>Stoperler (CB) merkezi bölgelerde görev yapar.</li><li>Bekler (LB &amp; RB) savunmada geniş oynar.</li><li>Kanat bekleri (LWB &amp; RWB) daha ofansif beklerdir.</li></ul><h2><strong>3. Orta Saha Oyuncuları</strong></h2><ul><li>Defansif orta saha oyuncuları (CDM) savunmayı korur.</li><li>Merkez orta saha oyuncuları (CM) savunma görevlerini ileri paslarla dengeler.</li><li>Ofansif orta saha oyuncuları (CAM) rakibin kalesine daha yakın oynar.</li><li>Kanat orta saha oyuncuları (LM/RM) genişlik sağlar.</li></ul><h2><strong>4. Forvetler</strong></h2><ul><li>Forvetler (ST) tipik olarak hattı yönetir.</li><li>Santraforlar (CF) oyunu bağlamak için daha derine inebilir.</li><li>Kanatlar (LW/RW) savunmayı genişletir.</li></ul><h2><strong>5. Pozisyonel Oyunun Önemi</strong></h2><p>Bir takımın başarısı, her oyuncunun kendi sorumluluklarını ve pozisyonunun genel taktik plana nasıl uyduğunu anlamasına bağlıdır.</p>"
  }
} $json$::jsonb
WHERE slug = 'understanding-football-positions-and-their-roles';
