// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Safety check for environment variables
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error("Missing Supabase environment variables. Please check your .env file or Vercel settings.");
}

// Safety check for localStorage (some browsers/privacy modes block it)
let storage;
try {
  storage = window.localStorage;
} catch (e) {
  console.warn("localStorage is not available. Falling back to memory storage.", e);
  storage = undefined;
}

export const supabase = createClient<Database>(
  SUPABASE_URL || "", 
  SUPABASE_PUBLISHABLE_KEY || "", 
  {
    auth: {
      storage: storage,
      persistSession: !!storage,
      autoRefreshToken: true,
    }
  }
);